class SoftwareSourceCode
  # Properties from SoftwareSourceCode
  attr_accessor code_repository: String?
  attr_accessor code_sample_type: String?
  attr_accessor programming_language: String?
  attr_accessor runtime_platform: String?
  attr_accessor target_product: String?

  # Properties from CreativeWork
  attr_accessor about: Codemeta::Thing?
  attr_accessor abstract: String?
  attr_accessor access_mode: String?
  attr_accessor access_mode_sufficient: Array?
  attr_accessor accessibility_api: String?
  attr_accessor accessibility_control: String?
  attr_accessor accessibility_feature: String?
  attr_accessor accessibility_hazard: String?
  attr_accessor accessibility_summary: String?
  attr_accessor accountable_person: Codemeta::Person?
  attr_accessor aggregate_rating: Codemeta::AggregateRating?
  attr_accessor alternative_headline: String?
  attr_accessor archived_at: Codemeta::URL
  attr_accessor assesses: Codemeta::DefinedTerm? 
  attr_accessor associated_media: Codemeta::MediaObject?
  attr_accessor audience: Codemeta::Audience?
  attr_accessor audio: Codemeta::AudioObject?
  attr_accessor author: Codemeta::Person
  attr_accessor award: String?
  attr_accessor character: Codemeta::Person?
  attr_accessor citation: Codemeta::CreativeWork?
  attr_accessor comment: Codemeta::Comment?
  attr_accessor comment_count: Integer?
  attr_accessor conditions_of_access: String?
  attr_accessor content_location: Codemeta::Place?
  attr_accessor content_rating: String?
  attr_accessor content_reference_time: DateTime?
  attr_accessor contributor: Codemeta::Person?
  attr_accessor copyright_holder: Codemeta::Organization?
  attr_accessor copyright_notice: String?
  attr_accessor copyright_year: Integer?
  attr_accessor correction: Codemeta::URL?
  attr_accessor country_of_origin: Codemeta::Country?
  attr_accessor creative_work_status: String?
  attr_accessor creator: Codemeta::Person
  attr_accessor credit_text: String?
  attr_accessor date_created: DateTime
  attr_accessor date_modified: DateTime?
  attr_accessor date_published: DateTime?
  attr_accessor discussion_url: Codemeta::URL?
  attr_accessor edit_eidr: Codemeta::URL?
  attr_accessor editor: Codemeta::Person?
  attr_accessor educational_alignment: Codemeta::AlignmentObject?
  attr_accessor educational_level: String?
  attr_accessor educational_use: String?
  attr_accessor encoding: Codemeta::MediaObject?
  attr_accessor encoding_format: String?
  attr_accessor example_of_work: Codemeta::CreativeWork?
  attr_accessor expires: DateTime?
  attr_accessor funder: Codemeta::Organization?
  attr_accessor funding: Codemeta::Grant?
  attr_accessor genre: String?
  attr_accessor has_part: Codemeta::CreativeWork?
  attr_accessor headline: String?
  attr_accessor in_language: String?
  attr_accessor interaction_statistic: Codemeta::InteractionCounter?
  attr_accessor interactivity_type: String?
  attr_accessor interpreted_as_claim: Codemeta::Claim?
  attr_accessor is_accessible_for_free: Boolean?
  attr_accessor is_based_on: Codemeta::CreativeWork?
  attr_accessor is_family_friendly: Boolean?
  attr_accessor is_part_of: Codemeta::CreativeWork?
  attr_accessor keywords: String?
  attr_accessor learning_resource_type: String?
  attr_accessor license: Codemeta::URL?
  attr_accessor location_created: Codemeta::Place?
  attr_accessor main_entity: Codemeta::Thing?

  # Properties from Thing
  attr_accessor additional_type: Codemeta::URL?
  attr_accessor alternate_name: String?
  attr_accessor description: String?
  attr_accessor disambiguating_description: String?
  attr_accessor identifier: Codemeta::URL
  attr_accessor image: Codemeta::URL?
  attr_accessor main_entity_of_page: Codemeta::URL?
  attr_accessor name: String
  attr_accessor potential_action: Codemeta::Action?
  attr_accessor same_as: Codemeta::URL?
  attr_accessor subject_of: Codemeta::CreativeWork?
  attr_accessor url: Codemeta::URL
end
